/**
 * TDS (Tax Deducted at Source) live derivation — INDIA COMPLIANCE.
 *
 * Section selection precedence (CBDT circulars, FY 2025-26):
 *   - Default: Section 194-O (0.1% w.e.f. 1-Oct-2024, Finance (No. 2) Act 2024)
 *     since Familiarise is the e-commerce operator. Applies to RESIDENT
 *     participants; non-residents pivot to Sec 195 + DTAA (194-O does not apply
 *     to NR — tracked in #738).
 *   - Explicit override: `consultant.tdsSection` is honoured for
 *     consultants whose engagement is direct (not via the platform e.g.
 *     direct-invoice contractors). This pivots between 194-O / 194J / 194C.
 *   - 194-O takes precedence over 194J in mixed-flow cases (platform-
 *     as-intermediary precedence per CBDT).
 *
 * PAN fallback (old Section 206AA — Section 397(2) of the IT Act 2025
 * for deductions on/after 1 Apr 2026):
 *   - If `panNumber` is null OR doesn't match /^[A-Z]{5}[0-9]{4}[A-Z]$/,
 *     withhold at the 20% punitive rate. This wins over both DTAA and
 *     section default (it's the higher-of rule).
 *   - #785: callers whose PAN is encrypted at rest pass `panOnFile: true`
 *     (validated at collection) instead of the ciphertext — passing the
 *     ciphertext as `panNumber` fails the regex and wrongly hits the fallback.
 *
 * Lower-rate certificate (Section 197):
 *   - If `tdsLowerRateCert` is non-empty AND `tdsRate` is populated,
 *     use the cert's rate (which is taken from `consultant.tdsRate` —
 *     the schema doesn't carry a separate cert-rate column in v1).
 *
 * DTAA rate lookup (NON_RESIDENT only):
 *   - Cross-reference `providerCountry` against `dtaa-rates.json`.
 *   - Apply DTAA rate ONLY if it is strictly LOWER than the section
 *     default. India's TDS framework permits the LOWER of section vs
 *     DTAA — so a treaty rate of 10% never reduces a 0.1% Section 194-O.
 *   - Captures `dtaaRateApplied` on the Payout when applied; null
 *     otherwise.
 *
 * Removed provisions (DO NOT implement):
 *   - TCS Section 206C(1H): removed 1 Apr 2025.
 *   - Section 206AB (higher TDS for non-filers): omitted 1 Apr 2025.
 *   - Equalisation Levy (2% cross-border, 6% ads): abolished.
 *
 * Reporting: Quarterly TDS returns (Form 26Q / 27Q) generated by batch
 * job, not this lib. This lib only derives the per-payout numbers.
 *
 * ───────────────────────────────────────────────────────────────────────────
 * #778 §E — CONSOLIDATION TARGET (v1; CA-gated)
 *
 * This is the single TDS engine of record. The parallel consultant pipeline
 * `lib/payments/tax/tds-service.ts` (194J/₹50K) is slated for deprecation —
 * see its header for the step-by-step plan. When consultant payouts route here:
 *   - `ConsultantTaxInfo.taxEntityType` (#778 §D; canonical since the
 *     BLOCKER-0 dedup, #1230) selects the threshold/section for the
 *     residual 194J/194C cases (entity-type-aware withholding). Null until
 *     declared via /api/consultant/tax-info — reads as INELIGIBLE for the
 *     194-O ₹5L exemption (fail-closed).
 *   - `tdsSection` override stays the per-consultant escape hatch.
 *   - Rate inputs move Float→integer bps (#781 §C) so storage is exact.
 *   - Emit a `TdsAdjustment` (#778 §D) on refund-driven reversals instead of a
 *     bare negative `TDSRecord`.
 *   - Confirm every withholding posts to the TDS_PAYABLE ledger account.
 *
 * Blocked on written CA confirmation of 194-O precedence for consultant
 * payouts. Until then both engines run; default conservative.
 * ───────────────────────────────────────────────────────────────────────────
 */

import type { ConsultantProfile } from "@prisma/client";
import dtaaRatesJson from "./dtaa-rates.json";

/** Default rates per section. Update when CBDT changes the rate card. */
export const TDS_SECTION_DEFAULTS: Record<string, number> = {
  // #771 P0-1 / #737 / #738 — 194-O was cut to 0.1% (0.001) w.e.f. 1-Oct-2024 by
  // the Finance (No. 2) Act 2024. Previously wrongly 0.01 (1%) → 10x over-withholding.
  "194O": 0.001,
  "194J": 0.1,
  "194C": 0.02,
};

/** No-PAN punitive rate (old §206AA, now §397(2) IT Act 2025) — applies to 194J/194C. */
export const PAN_FALLBACK_RATE = 0.2;

/**
 * #771 P0-1 — the e-commerce (194-O) no-PAN rate is 5%, not the generic 20%.
 * Under the IT Act 2025 both live in §397(2): 20% default with an explicit 5%
 * e-commerce carve-out. Applied when the section is 194-O and PAN is
 * missing/invalid.
 */
export const NO_PAN_RATE_194O = 0.05;

/** Default section when none is explicitly set on the consultant. */
export const DEFAULT_SECTION = "194O";

const DTAA_RATES: Record<string, number> =
  (dtaaRatesJson as { rates: Record<string, number> }).rates ?? {};

export interface TdsComputation {
  tdsSection: string; // "194J" | "194O" | "194C"
  tdsRate: number; // decimal (0.10 = 10%)
  tdsAmountPaise: number;
  dtaaRateApplied: number | null;
  fallbackApplied: boolean; // true if 206AA/PAN-missing fallback triggered
  reason: string; // human-readable explanation for audit log
}

/**
 * The minimal shape `computeTdsForPayout` needs from a consultant. Lifted
 * out of `Pick<ConsultantProfile, ...>` so non-Prisma callers (synthetic
 * inputs from `OrganizationPayout` paths that don't carry a per-consultant
 * FK) can pass a structurally compatible object.
 */
export type TdsConsultantInput = {
  panNumber: string | null;
  /**
   * #785 — PAN is on file but stored ENCRYPTED at rest, so its plaintext format
   * can't be validated here. true ⟹ treat as a valid PAN for the rate decision
   * (validated at collection time). Payout callers MUST use this instead of
   * passing the ciphertext as `panNumber` — the ciphertext fails `isValidPan`
   * and wrongly triggers the higher no-PAN rate (5% vs 0.1% under 194-O).
   */
  panOnFile?: boolean;
  residencyStatus: ConsultantProfile["residencyStatus"];
  tdsSection: string | null;
  /** #781 §C — integer basis points (1000 = 10%); the engine's internal
   *  math stays decimal-fraction until the PR-C consolidation. */
  tdsRateBps: number | null;
  tdsLowerRateCert: string | null;
  providerCountry: string | null;
};

/**
 * Validates PAN format. PAN is exactly: 5 letters + 4 digits + 1 letter,
 * uppercase only. Used for Section 206AA fallback.
 */
export function isValidPan(pan: string | null | undefined): boolean {
  if (!pan) return false;
  return /^[A-Z]{5}[0-9]{4}[A-Z]$/.test(pan);
}

function decimalToNumber(value: number | null | undefined): number | null {
  if (value === null || value === undefined) return null;
  return value;
}

/**
 * Compute TDS for a payout to a consultant. Pure function — no side
 * effects, no DB reads. Caller passes in the consultant's tax fields.
 */
export function computeTdsForPayout(params: {
  grossAmountPaise: number;
  consultant: TdsConsultantInput;
}): TdsComputation {
  const { grossAmountPaise, consultant } = params;
  const reasons: string[] = [];

  // --- 1. Section selection
  const explicitSection = consultant.tdsSection ?? null;
  const tdsSection = explicitSection ?? DEFAULT_SECTION;
  const sectionDefaultRate =
    TDS_SECTION_DEFAULTS[tdsSection] ?? TDS_SECTION_DEFAULTS[DEFAULT_SECTION];
  if (explicitSection) {
    reasons.push(`section=${tdsSection} (explicit override)`);
  } else {
    reasons.push(`section=${tdsSection} (platform default)`);
  }

  // --- 2. PAN fallback — wins over everything else. #771 P0-1: 194-O has its
  // own 5% no-PAN rate; 206AA's 20% applies to 194J/194C. #785: a PAN counts as
  // present when a valid plaintext PAN is supplied OR panOnFile asserts an
  // encrypted-at-rest PAN — the ciphertext can't be format-checked here.
  const hasValidPan =
    consultant.panOnFile === true || isValidPan(consultant.panNumber);
  if (!hasValidPan) {
    const fallbackRate =
      tdsSection === "194O" ? NO_PAN_RATE_194O : PAN_FALLBACK_RATE;
    const amt = Math.floor(grossAmountPaise * fallbackRate);
    reasons.push(
      tdsSection === "194O"
        ? `Section 194-O no-PAN fallback → ${(NO_PAN_RATE_194O * 100).toFixed(0)}%`
        : `Section 206AA fallback (PAN missing or malformed) → ${(PAN_FALLBACK_RATE * 100).toFixed(0)}%`,
    );
    return {
      tdsSection,
      tdsRate: fallbackRate,
      tdsAmountPaise: amt,
      dtaaRateApplied: null,
      fallbackApplied: true,
      reason: reasons.join("; "),
    };
  }

  // --- 3. Section 197 lower-rate certificate — overrides section default
  // when both the cert ref AND a per-consultant rate are populated. The
  // schema doesn't carry a separate `tdsLowerRateCertRate` field, so we
  // re-purpose the consultant's rate (bps → fraction) as the cert's rate.
  const certRate =
    consultant.tdsRateBps === null ? null : consultant.tdsRateBps / 10_000;
  if (consultant.tdsLowerRateCert && certRate !== null) {
    const amt = Math.floor(grossAmountPaise * certRate);
    reasons.push(`Section 197 cert ${consultant.tdsLowerRateCert} → ${(certRate * 100).toFixed(2)}%`);
    return {
      tdsSection,
      tdsRate: certRate,
      tdsAmountPaise: amt,
      dtaaRateApplied: null,
      fallbackApplied: false,
      reason: reasons.join("; "),
    };
  }

  // --- 4. DTAA lookup (NON_RESIDENT only)
  let effectiveRate = sectionDefaultRate;
  let dtaaRateApplied: number | null = null;
  if (consultant.residencyStatus === "NON_RESIDENT") {
    const country = (consultant.providerCountry ?? "").toUpperCase();
    const dtaaRate = country ? DTAA_RATES[country] : undefined;
    if (dtaaRate === undefined) {
      reasons.push(`no DTAA entry for country=${country || "(none)"}`);
    } else if (dtaaRate < sectionDefaultRate) {
      effectiveRate = dtaaRate;
      dtaaRateApplied = dtaaRate;
      reasons.push(
        `DTAA ${country} ${(dtaaRate * 100).toFixed(2)}% applied (lower than section ${(sectionDefaultRate * 100).toFixed(2)}%)`,
      );
    } else {
      reasons.push(
        `DTAA ${country} ${(dtaaRate * 100).toFixed(2)}% NOT lower than section default ${(sectionDefaultRate * 100).toFixed(2)}% — section wins`,
      );
    }
  }

  const tdsAmountPaise = Math.floor(grossAmountPaise * effectiveRate);
  return {
    tdsSection,
    tdsRate: effectiveRate,
    tdsAmountPaise,
    dtaaRateApplied,
    fallbackApplied: false,
    reason: reasons.join("; "),
  };
}
