"use client";

import { useState } from "react";
import { useSearchParams } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  CreditCard,
  AlertCircle,
  Sparkles,
  Plus,
  Trash2,
  Lock,
} from "lucide-react";
import { z } from "zod";

import { useOrgRole, useRequireOrgAccess } from "../useOrgRole";
import {
  fetchOrgDetails,
  orgDetailsQueryKey,
} from "@/lib/api/organizations/org-details";
import { useToast } from "@/hooks/use-toast";
import { loadScript } from "@/app/checkout/plans/utils";
import { errorMessageFromBody, parseJsonResponse } from "@/lib/fetch-helpers";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  ResponsiveModal,
  ResponsiveModalContent,
  ResponsiveModalFooter,
  ResponsiveModalHeader,
  ResponsiveModalTitle,
} from "@/components/ui/responsive-modal";

import {
  DashboardHeader,
  DashboardContent,
  DashboardGrid,
} from "@/components/dashboard/PageScaffold";
import { StatCard } from "@/components/dashboard/StatCard";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  ResponsiveTable,
  type ResponsiveColumn,
} from "@/components/ui/responsive-table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { formatCurrencyAmount } from "@/utils/formatting";
import { FUNDING_SOURCE_LABEL } from "@/lib/labels/org-labels";
import { useSession } from "@/lib/auth-client";
import { buildRazorpayPrefill } from "@/lib/payments/razorpay-prefill";
import type {
  OrgReceivablePosting,
  OrgReceivablesPayload,
} from "@/lib/data/org-receivables";
import { WalletTab } from "./WalletTab";
import { BillingBlockBanner } from "@/components/billing/BillingBlockBanner";

// ---------------------------------------------------------------------------
// Zod schemas — narrow API responses at the network boundary so the rest
// of the component can rely on inferred types instead of `as` casts.
// ---------------------------------------------------------------------------

const billingSummarySchema = z.object({
  // #1427/#1430 — resolved server-side next to the account read; see
  // app/api/organizations/[orgId]/billing/route.ts.
  walletFrozen: z.boolean().default(false),
  walletFrozenReason: z.string().nullable().default(null),
  dunningSuspended: z.boolean().default(false),
  dunningSuspendedInvoiceNumber: z.string().nullable().default(null),
  fundingSource: z
    .enum(["PERSONAL", "WALLET", "INVOICE", "LICENSE"])
    .nullable(),
  monthToDate: z.object({
    gross: z.number(),
    paymentCount: z.number(),
  }),
  outstanding: z.object({
    amount: z.number(),
    invoiceCount: z.number(),
  }),
  // #777 §B: INVOICE-funded credit ceiling (paise; null/absent = unlimited).
  // Optional so the client tolerates the API until it ships the field —
  // when absent we treat the org as unlimited rather than inventing a cap.
  creditLimitPaise: z.number().nullable().optional(),
  pendingCharges: z
    .object({ amount: z.number(), paymentCount: z.number() })
    .nullable(),
  paymentTermsDays: z.number(),
  licenseContract: z
    .object({
      id: z.string(),
      effectiveFrom: z.string(),
      effectiveTo: z.string().nullable(),
      autoRenew: z.boolean(),
      subscription: z
        .object({
          model: z.enum(["PER_SEAT", "FLAT_FEE"]),
          cycle: z.enum(["MONTHLY", "QUARTERLY", "ANNUAL"]),
          flatFeePaise: z.number().nullable(),
          currentCycleStart: z.string(),
          currentCycleEnd: z.string(),
          nextInvoiceDate: z.string(),
        })
        .nullable(),
    })
    .nullable(),
});
type BillingSummary = z.infer<typeof billingSummarySchema>;

const orgInvoiceSchema = z.object({
  id: z.string(),
  invoiceNumber: z.string(),
  totalPaise: z.number(),
  displayCurrency: z.string(),
  status: z.enum(["DRAFT", "ISSUED", "PAID", "OVERDUE", "VOID", "CANCELLED"]),
  dueDate: z.string().nullable(),
  paidAt: z.string().nullable(),
  autoGenerated: z.boolean(),
  createdAt: z.string(),
});

type OrgInvoice = z.infer<typeof orgInvoiceSchema>;

const invoicesListResponseSchema = z.object({
  data: z.array(orgInvoiceSchema).default([]),
});

const invoicePayResponseSchema = z.object({
  razorpayOrderId: z.string().startsWith("order_"),
  keyId: z.string().min(1),
  amountPaise: z.number().int().positive(),
  currency: z.string().length(3),
  invoice: z.object({
    id: z.string(),
    invoiceNumber: z.string(),
    status: z.string(),
  }),
});
type InvoicePayResponse = z.infer<typeof invoicePayResponseSchema>;

// The per-invoice GET endpoint returns the full invoice + relations,
// but for the post-checkout poll we only care about `status`. Zod
// strips unknown fields by default so this narrow schema accepts the
// full payload and just lifts the one field we need.
const invoiceStatusPollSchema = z.object({
  invoice: z.object({
    status: z.enum(["DRAFT", "ISSUED", "PAID", "OVERDUE", "VOID", "CANCELLED"]),
  }),
});

// Same poll budget as the wallet flow (see credits/page.tsx) — 20s
// total, then we fall back to "awaiting confirmation" so the UI never
// stalls if Razorpay's webhook is slow.
const INVOICE_POLL_INTERVAL_MS = 1000;
const INVOICE_POLL_MAX_ATTEMPTS = 20;

// Discriminated union for the post-checkout flow:
//   - "confirmed": webhook landed within the poll budget; row is PAID.
//   - "pending":   capture succeeded but the webhook is slow.
//   - "not_paid":  popup dismissed or `payment.failed` fired (already
//      toasted); the success handler stays silent.
type InvoicePayMutationResult =
  | { result: InvoicePayResponse; outcome: "confirmed" }
  | { result: InvoicePayResponse; outcome: "pending" }
  | { result: InvoicePayResponse; outcome: "not_paid" };

async function fetchBilling(orgId: string): Promise<BillingSummary> {
  const res = await fetch(`/api/organizations/${orgId}/billing`);
  return parseJsonResponse(
    res,
    billingSummarySchema,
    "Failed to load billing summary",
  );
}

async function fetchInvoices(orgId: string) {
  const res = await fetch(
    `/api/organizations/${orgId}/billing-account/invoices?perPage=50`,
  );
  const parsed = await parseJsonResponse(
    res,
    invoicesListResponseSchema,
    "Failed to load invoices",
  );
  return { invoices: parsed.data };
}

async function generateInvoice(orgId: string) {
  const res = await fetch(
    `/api/organizations/${orgId}/billing/generate-invoice`,
    { method: "POST" },
  );
  const body = await res.json().catch(() => null);
  if (!res.ok)
    throw new Error(errorMessageFromBody(body, "Failed to generate invoice"));
  return body;
}

async function payInvoice(
  orgId: string,
  invoiceId: string,
): Promise<InvoicePayResponse> {
  const res = await fetch(
    `/api/organizations/${orgId}/billing-account/invoices/${invoiceId}/pay`,
    { method: "POST" },
  );
  return parseJsonResponse(
    res,
    invoicePayResponseSchema,
    "Failed to initiate payment",
  );
}

async function fetchInvoiceStatus(
  orgId: string,
  invoiceId: string,
): Promise<
  "DRAFT" | "ISSUED" | "PAID" | "OVERDUE" | "VOID" | "CANCELLED" | null
> {
  const res = await fetch(
    `/api/organizations/${orgId}/billing-account/invoices/${invoiceId}`,
  );
  if (!res.ok) return null;
  // Status poll runs in a tight loop; tolerate a transient
  // contract-drift parse failure rather than throwing the loop —
  // worst case we keep polling until the budget elapses.
  const parsed = invoiceStatusPollSchema.safeParse(await res.json());
  return parsed.success ? parsed.data.invoice.status : null;
}

/**
 * Poll the invoice endpoint until the webhook flips `status` to
 * `PAID` or the budget elapses. Returns `true` on confirmation,
 * `false` on timeout. The webhook handler (`handleOrgPaymentSuccess`)
 * is the source of truth — this exists purely so the UI doesn't lie
 * about state for ~5–20s after a successful capture.
 */
async function pollInvoiceUntilPaid(
  orgId: string,
  invoiceId: string,
): Promise<boolean> {
  for (let attempt = 0; attempt < INVOICE_POLL_MAX_ATTEMPTS; attempt++) {
    const status = await fetchInvoiceStatus(orgId, invoiceId);
    if (status === "PAID") return true;
    await new Promise((r) => setTimeout(r, INVOICE_POLL_INTERVAL_MS));
  }
  return false;
}

// FDE: whole days an OVERDUE invoice is past its dueDate (falling back to
// createdAt when dueDate is null). Ceiled so a freshly-flipped row reads
// "1 day late" — never "0 days late"; 0 only when not actually past due.
function daysLate(dueDate: string | null, createdAt: string): number {
  const ref = new Date(dueDate ?? createdAt).getTime();
  const diffMs = Date.now() - ref;
  if (diffMs <= 0) return 0;
  return Math.ceil(diffMs / (24 * 60 * 60 * 1000));
}

// Stateless; module scope keeps the component's cognitive complexity down.
const receivableColumns: ResponsiveColumn<OrgReceivablePosting>[] = [
  {
    key: "posted",
    header: "Posted",
    primary: true,
    className: "text-xs text-muted-foreground",
    cell: (p) => new Date(p.postedAt).toLocaleDateString(),
  },
  {
    key: "movement",
    header: "Movement",
    cell: (p) => (
      <Badge variant={p.movement === "ACCRUED" ? "outline" : "default"}>
        {p.movement === "ACCRUED" ? "Accrued" : "Cleared"}
      </Badge>
    ),
  },
  {
    key: "amount",
    header: "Amount",
    cell: (p) => formatCurrencyAmount(p.amountPaise, "INR"),
  },
  {
    key: "source",
    header: "Source",
    className: "font-mono text-xs",
    // Ids, not links: ADR 20's addendum is explicit that no org role has a
    // per-session page to open.
    cell: (p) => p.appointmentId ?? p.paymentId ?? p.invoiceId ?? "—",
  },
  {
    key: "status",
    header: "Status",
    className: "text-xs",
    // The receivable itself has no status — the ledger is append-only. What
    // an org can act on is the invoice that would clear it.
    cell: (p) =>
      p.invoiceStatus ?? (p.movement === "ACCRUED" ? "Not yet invoiced" : "—"),
  },
];

export function BillingPageClient({
  orgId,
  // #1319 — read on the server (lib/data/org-receivables) and handed down, so
  // the ledger is never queried from the browser. Null when the server gate
  // said no, which is the same case in which nothing below renders anyway.
  receivables = null,
}: {
  orgId: string;
  receivables?: OrgReceivablesPayload | null;
}) {
  // #1132 — invoice pay/create is `billing.manage` (OWNER + BILLING_ADMIN).
  const { can } = useOrgRole(orgId);
  const { allowed } = useRequireOrgAccess(orgId, {
    permission: "billing.read",
    canSponsor: true,
  });
  const searchParams = useSearchParams();
  const tabParam = searchParams?.get("tab");
  const initialTab =
    tabParam === "wallet" || tabParam === "receivables" ? tabParam : "invoices";
  const { data: session } = useSession();
  const queryClient = useQueryClient();

  const summary = useQuery({
    queryKey: ["org-billing", orgId],
    queryFn: () => fetchBilling(orgId),
    // Gate on role+capability so non-billable or non-MANAGER users
    // don't trigger a 403 before the redirect.
    enabled: allowed,
  });
  const invoices = useQuery({
    queryKey: ["org-billing-invoices", orgId],
    queryFn: () => fetchInvoices(orgId),
    enabled: allowed,
  });

  // #779 §B: read org status off the shared org-details cache (the layout
  // already fetched it) to drive the money-move affordance below. The
  // server still rejects top-up/pay when status !== ACTIVE; this just
  // stops the button being a dead click.
  const orgDetails = useQuery({
    queryKey: orgDetailsQueryKey(orgId),
    queryFn: () => fetchOrgDetails(orgId),
    staleTime: 60_000,
  });
  const orgStatus = orgDetails.data?.organization.status;
  // #1427/#1430 — a frozen wallet or a dunning-suspended org blocks the same
  // pay/top-up affordances as an unverified org; fold both into the one
  // gate rather than leaving the buttons live until checkout rejects them.
  const walletFrozen = summary.data?.walletFrozen ?? false;
  const dunningSuspended = summary.data?.dunningSuspended ?? false;
  const moneyMoveBlocked =
    orgStatus === "PENDING_VERIFICATION" ||
    orgStatus === "SUSPENDED" ||
    walletFrozen ||
    dunningSuspended;
  const moneyMoveReason = walletFrozen
    ? (summary.data?.walletFrozenReason ?? "Wallet spend is frozen")
    : dunningSuspended
      ? "Bookings are paused until the overdue invoice is settled"
      : orgStatus === "SUSPENDED"
        ? "Organization suspended"
        : "Verify your organization to move money";

  const generateMutation = useMutation({
    mutationFn: () => generateInvoice(orgId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["org-billing", orgId] });
      queryClient.invalidateQueries({
        queryKey: ["org-billing-invoices", orgId],
      });
    },
  });

  const { toast } = useToast();

  const payMutation = useMutation({
    mutationFn: async (
      invoiceId: string,
    ): Promise<InvoicePayMutationResult> => {
      const result = await payInvoice(orgId, invoiceId);

      const loaded = await loadScript(
        "https://checkout.razorpay.com/v1/checkout.js",
      ).catch(() => false);
      if (!loaded || !window.Razorpay) {
        throw new Error(
          "Razorpay checkout failed to load. Please disable ad-blockers and retry.",
        );
      }

      // The popup resolves with `paid: true` only if Razorpay's
      // `handler` fired (capture succeeded). Otherwise we treat the
      // attempt as not-yet-paid and skip polling — the row stays
      // ISSUED, no false "awaiting confirmation" toast.
      const prefill = buildRazorpayPrefill({
        name: session?.user?.name ?? null,
        email: session?.user?.email ?? null,
        phone: session?.user?.phone ?? null,
      });
      const paid = await new Promise<boolean>((resolve) => {
        const rzp = new window.Razorpay({
          key: result.keyId,
          amount: result.amountPaise,
          currency: result.currency,
          name: "Familiarise",
          description: `Invoice ${result.invoice.invoiceNumber}`,
          order_id: result.razorpayOrderId,
          ...(Object.keys(prefill).length > 0 ? { prefill } : {}),
          handler: () => {
            resolve(true);
          },
          theme: { color: "#2563EB" },
        });
        rzp.on("payment.failed", () => {
          toast({
            title: "Payment failed",
            description:
              "Your card was declined or the payment timed out. Please try again.",
            variant: "destructive",
          });
          resolve(false);
        });
        rzp.open();
      });

      if (!paid) {
        // Either payment.failed fired (already toasted) or the user
        // dismissed the popup. Skip polling and let the caller show
        // nothing extra.
        return { result, outcome: "not_paid" };
      }

      // Bridge the webhook-settlement race so the row flips to PAID
      // without the user manually refreshing. `outcome === "pending"`
      // means the budget elapsed; the capture is still safe (webhook
      // is idempotent on `OrganizationInvoice.providerOrderId`).
      const confirmed = await pollInvoiceUntilPaid(orgId, invoiceId);
      return { result, outcome: confirmed ? "confirmed" : "pending" };
    },
    onSuccess: ({ result, outcome }) => {
      queryClient.invalidateQueries({
        queryKey: ["org-billing-invoices", orgId],
      });
      queryClient.invalidateQueries({
        queryKey: ["org-billing", orgId],
      });
      if (outcome === "confirmed") {
        toast({
          title: "Invoice paid",
          description: `Invoice ${result.invoice.invoiceNumber} is now marked as PAID.`,
        });
      } else if (outcome === "pending") {
        toast({
          title: "Payment received",
          description:
            "Awaiting confirmation from Razorpay. The invoice will flip to PAID once the webhook lands.",
        });
      }
      // outcome === "not_paid" — payment.failed already toasted, or
      // the user dismissed the popup; stay silent.
    },
    onError: (err) => {
      toast({
        title: "Payment could not be initiated",
        description: err instanceof Error ? err.message : String(err),
        variant: "destructive",
      });
    },
  });

  // Manual invoice composer state
  const [showComposer, setShowComposer] = useState(false);
  const [lineItems, setLineItems] = useState([
    { description: "", quantity: 1, unitPrice: "" },
  ]);
  const [taxRate, setTaxRate] = useState("");
  const [gstin, setGstin] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [composerError, setComposerError] = useState<string | null>(null);

  if (!allowed) return null;

  async function createInvoice() {
    setComposerError(null);
    const items = lineItems
      .filter((li) => li.description.trim())
      .map((li) => ({
        description: li.description.trim(),
        quantity: li.quantity,
        unitPrice: Math.round(parseFloat(li.unitPrice || "0") * 100),
      }));
    if (items.length === 0) {
      setComposerError("Add at least one line item.");
      return;
    }
    const res = await fetch(
      `/api/organizations/${orgId}/billing-account/invoices`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          items,
          // Default due date: 60 days from today (NET-60) if not supplied.
          dueDate:
            dueDate ||
            new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
          issueImmediately: true,
        }),
      },
    );
    const body = await res.json();
    if (!res.ok) {
      setComposerError(errorMessageFromBody(body, "Failed to create invoice"));
      return;
    }
    queryClient.invalidateQueries({
      queryKey: ["org-billing-invoices", orgId],
    });
    setShowComposer(false);
    setLineItems([{ description: "", quantity: 1, unitPrice: "" }]);
  }

  const invoiceColumns: ResponsiveColumn<OrgInvoice>[] = [
    {
      key: "number",
      header: "Number",
      primary: true,
      className: "font-mono text-xs",
      cell: (inv) => inv.invoiceNumber,
    },
    {
      key: "amount",
      header: "Amount",
      cell: (inv) => formatCurrencyAmount(inv.totalPaise, inv.displayCurrency),
    },
    {
      key: "status",
      header: "Status",
      cell: (inv) => (
        <Badge
          variant={
            inv.status === "PAID"
              ? "default"
              : inv.status === "OVERDUE"
                ? "destructive"
                : "outline"
          }
        >
          {/* FDE: quantify the lateness so OVERDUE isn't an
              undated alarm — "OVERDUE · 5 days late". */}
          {inv.status === "OVERDUE"
            ? `OVERDUE · ${daysLate(inv.dueDate, inv.createdAt)} days late`
            : inv.status}
        </Badge>
      ),
    },
    {
      key: "due",
      header: "Due",
      className: "text-xs text-muted-foreground",
      cell: (inv) =>
        inv.dueDate ? new Date(inv.dueDate).toLocaleDateString() : "—",
    },
  ];

  // #1169 residual — every ORG_RECEIVABLE posting on this org, read-only. A
  // DEBIT is the org taking on an obligation; a CREDIT is it being discharged.
  // Per ADR 20 the source ids are all a posting says about the session behind
  // it, which is what an accounts-payable team needs to tie a line to a
  // booking and is also all it is entitled to.

  // Pay is gated to OWNER on the API; mirror that here so non-owners don't
  // see a button that will 403 on click. MAINTAINERs can view the invoice
  // but only the billing owner pays. Returns null (no action) otherwise.
  const renderInvoiceActions = (inv: OrgInvoice) =>
    (inv.status === "ISSUED" || inv.status === "OVERDUE") &&
    can("billing.manage") ? (
      <Button
        size="sm"
        variant={inv.status === "OVERDUE" ? "default" : "outline"}
        onClick={() => payMutation.mutate(inv.id)}
        // #779 §B: disable when the org can't move money; the server rejects
        // anyway, this kills the dead click. `title` carries the reason.
        disabled={payMutation.isPending || moneyMoveBlocked}
        title={moneyMoveBlocked ? moneyMoveReason : undefined}
      >
        Pay now
      </Button>
    ) : null;

  return (
    <>
      <DashboardHeader
        title="Billing"
        subtitle="Invoices, charges, and outstanding balance"
        actions={
          <div className="flex gap-2">
            {/* Wave-4b (#1230) — register export for finance reconciliation. */}
            <a
              href={`/api/organizations/${orgId}/billing-account/invoices/export`}
              className="inline-flex h-8 items-center rounded-md border px-3 text-sm hover:bg-zinc-50"
            >
              Export CSV
            </a>
            {can("billing.manage") && (
              <Button
                size="sm"
                variant="outline"
                onClick={() => setShowComposer(true)}
              >
                <Plus className="h-4 w-4 mr-1" /> Create invoice
              </Button>
            )}
            {can("billing.manage") &&
              summary.data?.fundingSource === "INVOICE" && (
                <Button
                  size="sm"
                  onClick={() => generateMutation.mutate()}
                  disabled={generateMutation.isPending}
                >
                  <Sparkles className="h-4 w-4 mr-1" /> Generate invoice
                </Button>
              )}
          </div>
        }
      />
      <DashboardContent>
        <Tabs defaultValue={initialTab}>
          <TabsList>
            <TabsTrigger value="invoices">Invoices</TabsTrigger>
            <TabsTrigger value="receivables">Receivables</TabsTrigger>
            <TabsTrigger value="wallet">Wallet</TabsTrigger>
          </TabsList>

          <TabsContent value="invoices" className="space-y-6">
            {/* Annual License panel — surfaces the LICENSE commercial
                value (fee, cycle, renewal, auto-renew) that the
                contract create flow (T5 / #756 GS-1) captures into
                BillingSubscription. Renders only when funding=LICENSE
                AND a subscription has been recorded; LICENSE orgs
                without a subscription see no panel (the contract was
                created with the fee field skipped). */}
            {summary.data?.fundingSource === "LICENSE" &&
              summary.data.licenseContract?.subscription && (
                <Card>
                  <CardHeader>
                    <CardTitle className="text-base">Annual License</CardTitle>
                    <CardDescription>
                      Pre-paid flat-fee contract. Bookings under this org
                      consume no per-session charge — they&apos;re covered by
                      this license.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <dl className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-3 text-sm">
                      <div>
                        <dt className="text-muted-foreground">Fee</dt>
                        <dd className="font-medium">
                          {/* FDE: a fee-less LICENSE contract is incomplete,
                              not free — say so rather than rendering ₹0.00
                              which reads as "no charge". Required by renewal. */}
                          {summary.data.licenseContract.subscription
                            .flatFeePaise == null ? (
                            <span className="text-amber-600">
                              (fee not recorded){" "}
                              <span className="text-xs font-normal text-muted-foreground/70">
                                — required before renewal
                              </span>
                            </span>
                          ) : (
                            <>
                              {formatCurrencyAmount(
                                summary.data.licenseContract.subscription
                                  .flatFeePaise,
                                "INR",
                              )}{" "}
                              /{" "}
                              {summary.data.licenseContract.subscription.cycle.toLowerCase()}
                            </>
                          )}
                        </dd>
                      </div>
                      <div>
                        <dt className="text-muted-foreground">Current cycle</dt>
                        <dd className="font-medium">
                          {new Date(
                            summary.data.licenseContract.subscription
                              .currentCycleStart,
                          ).toLocaleDateString("en-IN", {
                            day: "2-digit",
                            month: "short",
                            year: "numeric",
                          })}{" "}
                          →{" "}
                          {new Date(
                            summary.data.licenseContract.subscription
                              .currentCycleEnd,
                          ).toLocaleDateString("en-IN", {
                            day: "2-digit",
                            month: "short",
                            year: "numeric",
                          })}
                        </dd>
                      </div>
                      <div>
                        <dt className="text-muted-foreground">Next renewal</dt>
                        <dd className="font-medium">
                          {new Date(
                            summary.data.licenseContract.subscription
                              .nextInvoiceDate,
                          ).toLocaleDateString("en-IN", {
                            day: "2-digit",
                            month: "short",
                            year: "numeric",
                          })}
                        </dd>
                      </div>
                      <div>
                        <dt className="text-muted-foreground">Auto-renew</dt>
                        <dd className="font-medium">
                          {summary.data.licenseContract.autoRenew
                            ? "Enabled"
                            : "Disabled"}
                        </dd>
                      </div>
                    </dl>
                  </CardContent>
                </Card>
              )}
            {summary.isLoading ? (
              <p className="text-sm text-muted-foreground">Loading…</p>
            ) : summary.isError || !summary.data ? (
              /* The `?? 0` fallbacks below meant a failed fetch rendered
                 "₹0.00 outstanding" — an org carrying ₹40L of unpaid
                 invoices saw zero when the API 500'd. On a billing surface
                 that is worse than showing nothing. */
              <div className="rounded-lg border border-border bg-card p-6 text-sm">
                <p className="font-medium text-foreground">
                  Couldn&apos;t load the billing summary
                </p>
                <p className="mt-1 text-muted-foreground">
                  These figures are unavailable right now — this is a loading
                  problem, not a zero balance. Refresh to try again.
                </p>
              </div>
            ) : (
              <DashboardGrid columns={4}>
                <StatCard
                  title="This month gross"
                  value={formatCurrencyAmount(
                    summary.data?.monthToDate.gross ?? 0,
                    "INR",
                  )}
                  subtitle={`${summary.data?.monthToDate.paymentCount ?? 0} bookings`}
                  icon={CreditCard}
                  variant="success"
                />
                <StatCard
                  title="Outstanding"
                  value={formatCurrencyAmount(
                    summary.data?.outstanding.amount ?? 0,
                    "INR",
                  )}
                  subtitle={`${summary.data?.outstanding.invoiceCount ?? 0} invoices`}
                  icon={AlertCircle}
                  variant={
                    (summary.data?.outstanding.invoiceCount ?? 0) > 0
                      ? "warning"
                      : "default"
                  }
                />
                {summary.data?.pendingCharges && (
                  <StatCard
                    title="Pending charges"
                    value={formatCurrencyAmount(
                      summary.data.pendingCharges.amount,
                      "INR",
                    )}
                    subtitle={`${summary.data.pendingCharges.paymentCount} unbilled`}
                    icon={CreditCard}
                  />
                )}
                {/* Payment terms only apply to INVOICE-funded orgs.
                    WALLET orgs pre-fund their balance, LICENSE orgs pay
                    a flat fee — neither has NET-X invoice billing, so
                    showing NET-60 there is misleading. Mirrors the
                    contracts/page.tsx + form fix for T4/T5. */}
                {summary.data?.fundingSource !== "WALLET" &&
                  summary.data?.fundingSource !== "LICENSE" && (
                    <StatCard
                      title="Payment terms"
                      value={`NET-${summary.data?.paymentTermsDays ?? 60}`}
                    />
                  )}
                {summary.data?.fundingSource && (
                  <StatCard
                    title="Funding source"
                    value={FUNDING_SOURCE_LABEL[summary.data.fundingSource]}
                  />
                )}
              </DashboardGrid>
            )}

            {/* #777 §B: INVOICE-funded credit ceiling vs. live outstanding
                (issued+overdue). `creditLimitPaise` null/absent = unlimited;
                we say so rather than fabricating a cap. "Used" reuses the
                outstanding total already aggregated by the billing query. */}
            {summary.data?.fundingSource === "INVOICE" && (
              <p className="text-sm text-muted-foreground">
                {summary.data.creditLimitPaise == null ? (
                  <>
                    {formatCurrencyAmount(
                      summary.data.outstanding.amount,
                      "INR",
                    )}{" "}
                    outstanding · no credit limit set (unlimited)
                  </>
                ) : (
                  <>
                    {formatCurrencyAmount(
                      summary.data.outstanding.amount,
                      "INR",
                    )}{" "}
                    of{" "}
                    {formatCurrencyAmount(summary.data.creditLimitPaise, "INR")}{" "}
                    credit limit used
                    {summary.data.outstanding.amount >=
                      summary.data.creditLimitPaise && (
                      <span className="ml-1 font-medium text-amber-600">
                        — limit reached
                      </span>
                    )}
                  </>
                )}
              </p>
            )}

            {/* #1427/#1430 — the freeze/dunning states get the shared
                banner (with the support link); org-verification status
                keeps its own inline reason below. */}
            <BillingBlockBanner
              walletFrozen={walletFrozen}
              walletFrozenReason={summary.data?.walletFrozenReason}
              dunningSuspended={dunningSuspended}
              supportHref={`/dashboard/organization/${orgId}/support`}
            />

            {/* #779 §B: org can't move money until ACTIVE; surface the reason
                inline so the disabled Pay/Top-up affordances aren't silent. */}
            {moneyMoveBlocked && !walletFrozen && !dunningSuspended && (
              <div className="flex items-start gap-2 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">
                <Lock className="mt-0.5 h-4 w-4 shrink-0" />
                <p>
                  {moneyMoveReason}. Paying invoices and wallet top-ups are
                  disabled until then.
                </p>
              </div>
            )}

            <Card className="mt-6">
              <CardHeader>
                <CardTitle className="text-base">Invoices</CardTitle>
                <CardDescription>
                  Manual + auto-generated invoices for this organization.
                </CardDescription>
              </CardHeader>
              <CardContent>
                {invoices.isLoading ? (
                  <p className="text-sm text-muted-foreground">Loading…</p>
                ) : (
                  <ResponsiveTable<OrgInvoice>
                    columns={invoiceColumns}
                    rows={invoices.data?.invoices ?? []}
                    getRowId={(inv) => inv.id}
                    rowActions={renderInvoiceActions}
                    empty={
                      <p className="text-center text-sm text-muted-foreground py-6">
                        {summary.data?.fundingSource === "LICENSE"
                          ? summary.data.licenseContract?.subscription
                            ? "LICENSE-funded orgs don't generate per-booking invoices. See the Annual License panel above."
                            : "LICENSE-funded orgs don't generate per-booking invoices. The annual license fee covers all usage."
                          : "No invoices yet."}
                      </p>
                    }
                  />
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="receivables">
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Receivables</CardTitle>
                <CardDescription>
                  What this organization has consumed and not yet paid for,
                  posting by posting. A sponsored booking accrues here and an
                  invoice payment clears it, so a charge appears on this list
                  before it appears on any invoice. The ledger is append-only:
                  nothing on this page can be edited, and a correction is a
                  later counter-posting rather than a change to a row.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <DashboardGrid>
                  <StatCard
                    title="Outstanding"
                    value={formatCurrencyAmount(
                      receivables?.outstandingPaise ?? 0,
                      "INR",
                    )}
                  />
                  <StatCard
                    title="Accrued to date"
                    value={formatCurrencyAmount(
                      receivables?.accruedPaise ?? 0,
                      "INR",
                    )}
                  />
                  <StatCard
                    title="Cleared to date"
                    value={formatCurrencyAmount(
                      receivables?.clearedPaise ?? 0,
                      "INR",
                    )}
                  />
                </DashboardGrid>

                <ResponsiveTable<OrgReceivablePosting>
                  columns={receivableColumns}
                  rows={receivables?.postings ?? []}
                  getRowId={(p) => p.entryId}
                  empty={
                    <p className="text-center text-sm text-muted-foreground py-6">
                      Nothing has been accrued against this organization yet.
                      Wallet-funded and license-funded bookings never accrue
                      here — only invoice-funded ones, and any shortfall a
                      wallet debit could not cover.
                    </p>
                  }
                />

                {receivables &&
                  receivables.totalPostings > receivables.postings.length && (
                    <p className="text-xs text-muted-foreground">
                      Showing the {receivables.postings.length} most recent of{" "}
                      {receivables.totalPostings} postings. The totals above
                      cover all of them.
                    </p>
                  )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="wallet">
            <WalletTab
              orgId={orgId}
              moneyMoveBlocked={moneyMoveBlocked}
              moneyMoveReason={moneyMoveReason}
            />
          </TabsContent>
        </Tabs>
      </DashboardContent>

      {/* Manual invoice composer dialog */}
      <ResponsiveModal open={showComposer} onOpenChange={setShowComposer}>
        <ResponsiveModalContent className="sm:max-w-lg">
          <ResponsiveModalHeader>
            <ResponsiveModalTitle>Create manual invoice</ResponsiveModalTitle>
          </ResponsiveModalHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Line items</Label>
              {lineItems.map((li, i) => (
                <div key={i} className="flex gap-2 items-end">
                  <Input
                    placeholder="Description"
                    value={li.description}
                    onChange={(e) => {
                      const next = [...lineItems];
                      next[i] = { ...next[i], description: e.target.value };
                      setLineItems(next);
                    }}
                    className="flex-1"
                  />
                  <Input
                    placeholder="Qty"
                    type="number"
                    min={1}
                    value={li.quantity}
                    onChange={(e) => {
                      const next = [...lineItems];
                      next[i] = {
                        ...next[i],
                        quantity: parseInt(e.target.value) || 1,
                      };
                      setLineItems(next);
                    }}
                    className="w-16"
                  />
                  <Input
                    placeholder="Price (INR)"
                    type="number"
                    min={0}
                    step="0.01"
                    value={li.unitPrice}
                    onChange={(e) => {
                      const next = [...lineItems];
                      next[i] = { ...next[i], unitPrice: e.target.value };
                      setLineItems(next);
                    }}
                    className="w-28"
                  />
                  {lineItems.length > 1 && (
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() =>
                        setLineItems(lineItems.filter((_, j) => j !== i))
                      }
                    >
                      <Trash2 className="h-4 w-4 text-red-400" />
                    </Button>
                  )}
                </div>
              ))}
              <Button
                variant="outline"
                size="sm"
                onClick={() =>
                  setLineItems([
                    ...lineItems,
                    { description: "", quantity: 1, unitPrice: "" },
                  ])
                }
              >
                <Plus className="h-4 w-4 mr-1" /> Add line
              </Button>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="inv-tax">Tax rate (0-1)</Label>
                <Input
                  id="inv-tax"
                  type="number"
                  min="0"
                  max="1"
                  step="0.01"
                  value={taxRate}
                  onChange={(e) => setTaxRate(e.target.value)}
                  placeholder="e.g., 0.18"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="inv-gstin">GSTIN</Label>
                <Input
                  id="inv-gstin"
                  value={gstin}
                  onChange={(e) => setGstin(e.target.value)}
                  placeholder="Optional"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="inv-due">Due date</Label>
              <Input
                id="inv-due"
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
              />
            </div>
            {composerError && (
              <p className="text-sm text-red-600">{composerError}</p>
            )}
          </div>
          <ResponsiveModalFooter>
            <Button variant="outline" onClick={() => setShowComposer(false)}>
              Cancel
            </Button>
            <Button onClick={createInvoice}>Create invoice</Button>
          </ResponsiveModalFooter>
        </ResponsiveModalContent>
      </ResponsiveModal>
    </>
  );
}
