/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8lXFY4wZYdc
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export default function ConsultantDashboard() {
  return (
    <div className="bg-gray-100 p-40">
      <header className="flex items-center justify-between pb-6">
        <div className="flex items-center">
          <div className="mr-6">
            <Avatar>
              <AvatarImage alt="Mike Steele" src="/placeholder.svg" />
              <AvatarFallback>MS</AvatarFallback>
            </Avatar>
          </div>
          <div>
            <h1 className="text-2xl font-semibold">Mike Steele</h1>
            <p className="text-sm text-gray-500">Manager</p>
          </div>
        </div>
        <div className="flex space-x-4">
          <SettingsIcon className="text-gray-500" />
          <SignalIcon className="text-gray-500" />
          <SearchIcon className="text-gray-500" />
        </div>
      </header>
      <main className="grid grid-cols-12 gap-6">
        <aside className="col-span-2">
          <nav className="space-y-1">
            <Link className="block p-3 rounded-lg bg-blue-500 text-white" href="#">
              Home
            </Link>
            <Link className="block p-3 rounded-lg text-gray-600 hover:bg-gray-200" href="#">
              Calendar
            </Link>
            <Link className="block p-3 rounded-lg text-gray-600 hover:bg-gray-200" href="#">
              CRM
            </Link>
            <Link className="block p-3 rounded-lg text-gray-600 hover:bg-gray-200" href="#">
              Documents
            </Link>
            <Link className="block p-3 rounded-lg text-gray-600 hover:bg-gray-200" href="#">
              Reports
            </Link>
            <Link className="block p-3 rounded-lg text-gray-600 hover:bg-gray-200" href="#">
              Help
            </Link>
            <Link className="block p-3 rounded-lg text-gray-600 hover:bg-gray-200" href="#">
              Logout
            </Link>
          </nav>
          <div className="mt-6 p-4 bg-white rounded-lg shadow">
            <h2 className="text-lg font-semibold mb-2">Upgrade Now</h2>
            <p className="text-sm text-gray-600 mb-4">Find out what an improved account offers</p>
            <Button className="bg-blue-500 text-white">Explore Plans</Button>
          </div>
        </aside>
        <section className="col-span-10">
          <div className="grid grid-cols-3 gap-6">
            <div className="col-span-2">
              <div className="bg-white p-6 rounded-lg shadow">
                <h2 className="text-xl font-semibold mb-4">Today's Appointments</h2>
                <div className="grid grid-cols-2 gap-4">
                  <Card className="bg-purple-100">
                    <CardHeader>
                      <Avatar>
                        <AvatarImage alt="Olga Nunez" src="/placeholder.svg" />
                        <AvatarFallback>ON</AvatarFallback>
                      </Avatar>
                      <div>
                        <CardTitle>Olga Nunez</CardTitle>
                        <CardDescription>Invoice Negotiation</CardDescription>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm">3:00 PM - 3:30 PM</p>
                    </CardContent>
                    <CardFooter className="flex justify-between">
                      <Badge variant="secondary" className="bg-blue-500 text-white">Meeting in 5 min</Badge>
                      <Button variant="default"className="bg-black text-white">Join meet</Button>
                    </CardFooter>
                  </Card>
                  <Card className="bg-purple-100">
                    <CardHeader>
                      <Avatar>
                        <AvatarImage alt="Olga Nunez" src="/placeholder.svg" />
                        <AvatarFallback>ON</AvatarFallback>
                      </Avatar>
                      <div>
                        <CardTitle>Olga Nunez</CardTitle>
                        <CardDescription>Invoice Negotiation</CardDescription>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm">3:00 PM - 3:30 PM</p>
                    </CardContent>
                    <CardFooter className="flex justify-between">
                      <Badge variant="secondary" className="bg-blue-500 text-white">Meeting in 2 hours</Badge>
                      <Button variant="default" className="bg-black text-white">Join meet</Button>
                    </CardFooter>
                  </Card>
                </div>
              </div>
              <div className="bg-white p-6 rounded-lg shadow mt-6">
                <h2 className="text-xl font-semibold mb-4">Document For Review</h2>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-[100px]">Invoice No.</TableHead>
                      <TableHead>Client Name</TableHead>
                      <TableHead>Document Title</TableHead>
                      <TableHead>Tags</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-medium">2150</TableCell>
                      <TableCell>Andrea Jennings</TableCell>
                      <TableCell>2020 - Tax Statement</TableCell>
                      <TableCell>
                        <Badge variant="secondary">2023</Badge>
                      </TableCell>
                      <TableCell>
                        <FileEditIcon className="text-gray-500" />
                        <DeleteIcon className="text-gray-500" />
                        <DownloadIcon className="text-gray-500" />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">2150</TableCell>
                      <TableCell>Stacey Larson</TableCell>
                      <TableCell>2020 - Tax Statement</TableCell>
                      <TableCell>
                        <Badge variant="secondary">2023</Badge>
                      </TableCell>
                      <TableCell>
                        <FileEditIcon className="text-gray-500" />
                        <DeleteIcon className="text-gray-500" />
                        <DownloadIcon className="text-gray-500" />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">2150</TableCell>
                      <TableCell>Yvonne Breiner</TableCell>
                      <TableCell>2020 - Tax Statement</TableCell>
                      <TableCell>
                        <Badge variant="secondary">2023</Badge>
                      </TableCell>
                      <TableCell>
                        <FileEditIcon className="text-gray-500" />
                        <DeleteIcon className="text-gray-500" />
                        <DownloadIcon className="text-gray-500" />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">2150</TableCell>
                      <TableCell>Steven Glover</TableCell>
                      <TableCell>2020 - Tax Statement</TableCell>
                      <TableCell>
                        <Badge variant="secondary">2023</Badge>
                      </TableCell>
                      <TableCell>
                        <FileEditIcon className="text-gray-500" />
                        <DeleteIcon className="text-gray-500" />
                        <DownloadIcon className="text-gray-500" />
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </div>
            <div>
              <div className="bg-white p-6 rounded-lg shadow">
                <h2 className="text-xl font-semibold mb-4">Clients Activity</h2>
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Avatar>
                        <AvatarImage alt="Stephen" src="/placeholder.svg" />
                        <AvatarFallback>S</AvatarFallback>
                      </Avatar>
                      <p className="ml-2">Stephen joined to 🎨 channel.</p>
                    </div>
                    <p className="text-sm text-gray-500">20m ago</p>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Avatar>
                        <AvatarImage alt="Stephen" src="/placeholder.svg" />
                        <AvatarFallback>S</AvatarFallback>
                      </Avatar>
                      <p className="ml-2">Stephen joined to 🎨 channel.</p>
                    </div>
                    <p className="text-sm text-gray-500">20m ago</p>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Avatar>
                        <AvatarImage alt="Stephen" src="/placeholder.svg" />
                        <AvatarFallback>S</AvatarFallback>
                      </Avatar>
                      <p className="ml-2">Stephen joined to 🎨 channel.</p>
                    </div>
                    <p className="text-sm text-gray-500">20m ago</p>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Avatar>
                        <AvatarImage alt="Stephen" src="/placeholder.svg" />
                        <AvatarFallback>S</AvatarFallback>
                      </Avatar>
                      <p className="ml-2">Stephen joined to 🎨 channel.</p>
                    </div>
                    <p className="text-sm text-gray-500">20m ago</p>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Avatar>
                        <AvatarImage alt="Stephen" src="/placeholder.svg" />
                        <AvatarFallback>S</AvatarFallback>
                      </Avatar>
                      <p className="ml-2">Stephen joined to 🎨 channel.</p>
                    </div>
                    <p className="text-sm text-gray-500">20m ago</p>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Avatar>
                        <AvatarImage alt="Stephen" src="/placeholder.svg" />
                        <AvatarFallback>S</AvatarFallback>
                      </Avatar>
                      <p className="ml-2">Stephen joined to 🎨 channel.</p>
                    </div>
                    <p className="text-sm text-gray-500">20m ago</p>
                  </div>
                </div>
                <Button className="mt-4 w-full bg-blue-500 text-white">Login Report</Button>
              </div>
              <div className="bg-white p-6 rounded-lg shadow mt-6">
                <h2 className="text-xl font-semibold mb-4">Upcoming Birthdays</h2>
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Avatar>
                        <AvatarImage alt="Jesus Cardoza" src="/placeholder.svg" />
                        <AvatarFallback>JC</AvatarFallback>
                      </Avatar>
                      <p className="ml-2">Jesus Cardoza</p>
                    </div>
                    <p className="text-sm text-gray-500">24 March</p>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Avatar>
                        <AvatarImage alt="Andrea Jennings" src="/placeholder.svg" />
                        <AvatarFallback>AJ</AvatarFallback>
                      </Avatar>
                      <p className="ml-2">Andrea Jennings</p>
                    </div>
                    <p className="text-sm text-gray-500">24 March</p>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Avatar>
                        <AvatarImage alt="Yvonne Breiner" src="/placeholder.svg" />
                        <AvatarFallback>YB</AvatarFallback>
                      </Avatar>
                      <p className="ml-2">Yvonne Breiner</p>
                    </div>
                    <p className="text-sm text-gray-500">24 March</p>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center">
                      <Avatar>
                        <AvatarImage alt="Gabriel Dennis" src="/placeholder.svg" />
                        <AvatarFallback>GD</AvatarFallback>
                      </Avatar>
                      <p className="ml-2">Gabriel Dennis</p>
                    </div>
                    <p className="text-sm text-gray-500">24 March</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}


function SettingsIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function SignalIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 20h.01" />
      <path d="M7 20v-4" />
      <path d="M12 20v-8" />
      <path d="M17 20V8" />
      <path d="M22 4v16" />
    </svg>
  )
}


function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function FileEditIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z" />
    </svg>
  )
}


function DeleteIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 5H9l-7 7 7 7h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2Z" />
      <line x1="18" x2="12" y1="9" y2="15" />
      <line x1="12" x2="18" y1="9" y2="15" />
    </svg>
  )
}


function DownloadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}
