/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yU6zQT3gE3B
 */
"use client"; // Mark as a Client Component

import { useToast } from "@/hooks/use-toast";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { NotificationPreferencesPanel } from "@/components/notifications";
import { SettingsSkeleton } from "@/components/dashboard/DashboardSkeletons";
import {
  CookiePreference,
  NotificationPreference,
  StaffProfile,
  User,
} from "@prisma/client"; // Import types
import {
  useMutation,
  useQuery,
  useQueryClient,
} from "@tanstack/react-query";
import { AlertTriangle, RefreshCw } from "lucide-react";
import { ChangeEvent, use, useEffect, useState } from "react";

// Define a type for the user with preferences
type UserWithPreferences = User & {
  notificationPreferences: NotificationPreference | null;
  cookiePreferences: CookiePreference | null;
};

// Define a type for the combined staff data (StaffProfile with nested user)
type StaffData = StaffProfile & {
  user: UserWithPreferences;
};

type PageProps = {
  params: Promise<{ staffId: string }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
};

export default function StaffSettingsPage({ params }: Readonly<PageProps>) {
  const resolvedParams = use(params);
  const { staffId } = resolvedParams;
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Fetch data on component mount
  const { data, isPending, isError, refetch } = useQuery({
    queryKey: ["staff-settings", staffId],
    queryFn: async (): Promise<StaffData> => {
      const response = await fetch(`/api/user/staff/${staffId}`);
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(
          errorData.error ||
            `Failed to fetch staff data: ${response.statusText}`,
        );
      }
      const result = await response.json();
      // API returns { data: StaffProfile } with user nested inside
      return result.data;
    },
  });

  // Local editable form state, seeded from the query result.
  const [staffData, setStaffData] = useState<StaffData | null>(null);

  // Seed the form once, on initial load. Later refetches (e.g. the invalidation
  // after a successful save) must NOT clobber in-progress edits — the save's own
  // onSuccess updates staffData explicitly with the server response.
  useEffect(() => {
    if (data && !staffData) setStaffData(data);
  }, [data, staffData]);

  // Handle input changes for user fields (name, email, phone, address, image)
  const handleUserInputChange = (
    e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => {
    const { name, value } = e.target;
    setStaffData((prev) => {
      if (!prev) return null;
      return {
        ...prev,
        user: {
          ...prev.user,
          [name]: value,
        },
      };
    });
  };

  const handleUserSelectChange = (value: string, name: string) => {
    setStaffData((prev) => {
      if (!prev) return null;
      return {
        ...prev,
        user: {
          ...prev.user,
          [name]: value,
        },
      };
    });
  };

  // Handle input changes for staff profile fields (department, position, etc.)
  const handleProfileInputChange = (
    e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => {
    const { name, value } = e.target;
    setStaffData((prev) => {
      if (!prev) return prev;
      return {
        ...prev,
        [name]: value,
      };
    });
  };

  const handleNotificationChange = (
    checked: boolean,
    name: keyof NotificationPreference,
  ) => {
    setStaffData((prev) => {
      if (!prev) return prev;
      const currentPrefs = prev.user.notificationPreferences ?? {
        userId: prev.user.id,
      }; // Create stub if null
      return {
        ...prev,
        user: {
          ...prev.user,
          notificationPreferences: {
            ...currentPrefs,
            [name]: checked,
          } as NotificationPreference, // Assert type
        },
      };
    });
  };

  const handleCookieChange = (
    checked: boolean,
    name: keyof CookiePreference,
  ) => {
    setStaffData((prev) => {
      if (!prev) return prev;
      const currentPrefs = prev.user.cookiePreferences ?? {
        userId: prev.user.id,
        essential: true,
      }; // Create stub if null
      return {
        ...prev,
        user: {
          ...prev.user,
          cookiePreferences: {
            ...currentPrefs,
            [name]: checked,
          } as CookiePreference, // Assert type
        },
      };
    });
  };

  // Generic save mutation - sends only changed data for a specific section
  const saveMutation = useMutation({
    mutationFn: async (
      section: "personal" | "role" | "account" | "preferences",
    ): Promise<{
      section: "personal" | "role" | "account" | "preferences";
      updatedData: StaffData;
    }> => {
      // Build payload - API expects flat object with both user and profile fields
      let payload: Record<string, unknown> = {};

      // Construct payload based on section
      switch (section) {
        case "personal":
          payload = {
            name: staffData!.user.name,
            email: staffData!.user.email,
            phone: staffData!.user.phone,
            address: staffData!.user.address,
            image: staffData!.user.image,
          };
          break;
        case "role":
          payload = {
            department: staffData!.department,
            position: staffData!.position,
          };
          break;
        case "account":
          payload = {
            timezone: staffData!.user.timezone,
          };
          break;
        case "preferences":
          payload = {
            allNotifications:
              staffData!.user.notificationPreferences?.allNotifications,
            mentions: staffData!.user.notificationPreferences?.mentions,
            directMessages:
              staffData!.user.notificationPreferences?.directMessages,
            updates: staffData!.user.notificationPreferences?.updates,
            analytics: staffData!.user.cookiePreferences?.analytics,
            marketing: staffData!.user.cookiePreferences?.marketing,
          };
          break;
      }

      const response = await fetch(`/api/user/staff/${staffId}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(
          errorData.error || `Failed to save ${section} settings`,
        );
      }

      const updatedData: StaffData = await response.json();
      return { section, updatedData };
    },
    onSuccess: ({ section, updatedData }) => {
      setStaffData(updatedData); // Update state with response data
      toast({
        title: "Settings saved",
        description: `${section.charAt(0).toUpperCase() + section.slice(1)} settings updated.`,
      });
      queryClient.invalidateQueries({
        queryKey: ["staff-settings", staffId],
      });
    },
    onError: (err: unknown, section) => {
      const errorMessage =
        err instanceof Error
          ? err.message
          : `An error occurred while saving ${section} settings`;
      toast({
        title: `Couldn't save ${section} settings`,
        description: errorMessage,
        variant: "destructive",
      });
    },
  });

  const handleSave = (
    section: "personal" | "role" | "account" | "preferences",
  ) => {
    if (!staffData) return;
    saveMutation.mutate(section);
  };

  // Render loading/error states
  if (isPending || (Boolean(data) && !staffData)) {
    return <SettingsSkeleton />;
  }
  if (isError && !data) {
    return (
      <div className="flex flex-col items-center justify-center gap-3 py-16 text-center">
        <div className="flex items-center gap-2 text-destructive">
          <AlertTriangle className="h-5 w-5" />
          <span>Failed to load settings.</span>
        </div>
        <Button
          variant="outline"
          size="sm"
          className="gap-2"
          onClick={() => refetch()}
        >
          <RefreshCw className="h-4 w-4" />
          Retry
        </Button>
      </div>
    );
  }
  if (!staffData) {
    return (
      <div className="flex items-center justify-center py-16">
        Staff member not found.
      </div>
    );
  }

  // Main component render
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Avatar className="h-16 w-16">
          <AvatarImage
            alt={staffData.user.name ?? "Staff"}
            src={staffData.user.image ?? "/placeholder.svg"}
          />
          <AvatarFallback>
            {staffData.user.name
              ?.split(" ")
              .map((n) => n[0])
              .join("") ?? "ST"}
          </AvatarFallback>
        </Avatar>
        <div className="min-w-0 space-y-1">
          <h1 className="text-fluid-2xl font-semibold tracking-tight text-foreground">
            Settings
          </h1>
          <p className="text-fluid-sm text-muted-foreground">
            Manage profile and account settings for{" "}
            {staffData.user.name ?? `Staff ID: ${staffId}`}.
          </p>
        </div>
      </div>

      {/* Settings Cards */}
      <div className="grid gap-6">
        {/* Personal Information Card */}
        <Card>
          <CardHeader>
            <CardTitle>Personal Information</CardTitle>
            <CardDescription>
              Update the staff member&apos;s personal details.
            </CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input
                id="name"
                name="name"
                placeholder="Full Name"
                value={staffData.user.name ?? ""}
                onChange={handleUserInputChange}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                name="email"
                type="email"
                placeholder="Email Address"
                value={staffData.user.email ?? ""}
                onChange={handleUserInputChange}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone">Phone</Label>
              <Input
                id="phone"
                name="phone"
                type="tel"
                placeholder="Phone Number"
                value={staffData.user.phone ?? ""}
                onChange={handleUserInputChange}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="address">Address</Label>
              <Textarea
                id="address"
                name="address"
                placeholder="Street Address"
                value={staffData.user.address ?? ""}
                onChange={handleUserInputChange}
                className="min-h-[80px]"
              />
            </div>
            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="image">Profile Picture URL</Label>
              <Input
                id="image"
                name="image"
                placeholder="https://example.com/avatar.png"
                value={staffData.user.image ?? ""}
                onChange={handleUserInputChange}
              />
            </div>
          </CardContent>
          <CardFooter className="border-t px-6 py-4">
            <Button
              onClick={() => handleSave("personal")}
              disabled={saveMutation.isPending}
            >
              {saveMutation.isPending ? "Saving..." : "Save Personal Info"}
            </Button>
          </CardFooter>
        </Card>

        {/* Staff Role Card */}
        <Card>
          <CardHeader>
            <CardTitle>Staff Role</CardTitle>
            <CardDescription>
              Manage the staff member&apos;s role and responsibilities.
            </CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="department">Department</Label>
              <Input
                id="department"
                name="department"
                placeholder="e.g., Engineering, Marketing"
                value={staffData.department ?? ""}
                onChange={handleProfileInputChange}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="position">Position</Label>
              <Input
                id="position"
                name="position"
                placeholder="e.g., Software Engineer, Manager"
                value={staffData.position ?? ""}
                onChange={handleProfileInputChange}
              />
            </div>
          </CardContent>
          <CardFooter className="border-t px-6 py-4">
            <Button
              onClick={() => handleSave("role")}
              disabled={saveMutation.isPending}
            >
              {saveMutation.isPending ? "Saving..." : "Save Role Info"}
            </Button>
          </CardFooter>
        </Card>

        {/* Account Settings Card */}
        <Card>
          <CardHeader>
            <CardTitle>Account Settings</CardTitle>
            <CardDescription>Manage account-related settings.</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4">
            <div className="space-y-2">
              <Label htmlFor="timezone">Timezone</Label>
              <Select
                name="timezone"
                value={staffData.user.timezone ?? ""}
                onValueChange={(value) =>
                  handleUserSelectChange(value, "timezone")
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select timezone" />
                </SelectTrigger>
                <SelectContent>
                  {/* Populate with actual timezones - Placeholder */}
                  <SelectItem value="America/New_York">
                    Eastern Time (US & Canada)
                  </SelectItem>
                  <SelectItem value="Europe/London">London</SelectItem>
                  <SelectItem value="Asia/Kolkata">
                    India Standard Time
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
          <CardFooter className="border-t px-6 py-4">
            <Button
              onClick={() => handleSave("account")}
              disabled={saveMutation.isPending}
            >
              {saveMutation.isPending ? "Saving..." : "Save Account Settings"}
            </Button>
          </CardFooter>
        </Card>

        {/* Novu Notification Preferences */}
        <NotificationPreferencesPanel />

        {/* Preferences Card */}
        <Card>
          <CardHeader>
            <CardTitle>Preferences</CardTitle>
            <CardDescription>
              Manage notification and cookie preferences.
            </CardDescription>
          </CardHeader>
          <CardContent className="grid gap-6">
            {/* Notification Preferences */}
            <div className="space-y-4">
              <h3 className="font-medium">Notifications</h3>
              <div className="flex items-center justify-between space-x-2">
                <Label
                  htmlFor="allNotifications"
                  className="flex flex-col space-y-1 cursor-pointer"
                >
                  <span>All Notifications</span>
                  <span className="font-normal leading-snug text-muted-foreground">
                    Enable or disable all notifications globally.
                  </span>
                </Label>
                <Switch
                  id="allNotifications"
                  name="allNotifications"
                  checked={
                    staffData.user.notificationPreferences?.allNotifications ??
                    false
                  }
                  onCheckedChange={(checked) =>
                    handleNotificationChange(checked, "allNotifications")
                  }
                />
              </div>
              <div className="flex items-center justify-between space-x-2">
                <Label
                  htmlFor="mentions"
                  className="flex flex-col space-y-1 cursor-pointer"
                >
                  <span>Mentions</span>
                  <span className="font-normal leading-snug text-muted-foreground">
                    Receive notifications for @mentions.
                  </span>
                </Label>
                <Switch
                  id="mentions"
                  name="mentions"
                  checked={
                    staffData.user.notificationPreferences?.mentions ?? false
                  }
                  onCheckedChange={(checked) =>
                    handleNotificationChange(checked, "mentions")
                  }
                />
              </div>
              <div className="flex items-center justify-between space-x-2">
                <Label
                  htmlFor="directMessages"
                  className="flex flex-col space-y-1 cursor-pointer"
                >
                  <span>Direct Messages</span>
                  <span className="font-normal leading-snug text-muted-foreground">
                    Receive notifications for direct messages.
                  </span>
                </Label>
                <Switch
                  id="directMessages"
                  name="directMessages"
                  checked={
                    staffData.user.notificationPreferences?.directMessages ??
                    false
                  }
                  onCheckedChange={(checked) =>
                    handleNotificationChange(checked, "directMessages")
                  }
                />
              </div>
              <div className="flex items-center justify-between space-x-2">
                <Label
                  htmlFor="updates"
                  className="flex flex-col space-y-1 cursor-pointer"
                >
                  <span>Platform Updates</span>
                  <span className="font-normal leading-snug text-muted-foreground">
                    Receive notifications about platform updates and news.
                  </span>
                </Label>
                <Switch
                  id="updates"
                  name="updates"
                  checked={
                    staffData.user.notificationPreferences?.updates ?? false
                  }
                  onCheckedChange={(checked) =>
                    handleNotificationChange(checked, "updates")
                  }
                />
              </div>
            </div>
            {/* Cookie Preferences */}
            <div className="space-y-4">
              <h3 className="font-medium">Cookie Preferences</h3>
              <div className="flex items-center justify-between space-x-2">
                <Label
                  htmlFor="essentialCookies"
                  className="flex flex-col space-y-1"
                >
                  <span>Essential Cookies</span>
                  <span className="font-normal leading-snug text-muted-foreground">
                    Required for basic site functionality. Cannot be disabled.
                  </span>
                </Label>
                <Switch
                  id="essentialCookies"
                  name="essential"
                  checked={staffData.user.cookiePreferences?.essential ?? true}
                  disabled
                />
              </div>
              <div className="flex items-center justify-between space-x-2">
                <Label
                  htmlFor="analyticsCookies"
                  className="flex flex-col space-y-1 cursor-pointer"
                >
                  <span>Analytics Cookies</span>
                  <span className="font-normal leading-snug text-muted-foreground">
                    Allow us to collect anonymous usage data.
                  </span>
                </Label>
                <Switch
                  id="analyticsCookies"
                  name="analytics"
                  checked={staffData.user.cookiePreferences?.analytics ?? false}
                  onCheckedChange={(checked) =>
                    handleCookieChange(checked, "analytics")
                  }
                />
              </div>
              <div className="flex items-center justify-between space-x-2">
                <Label
                  htmlFor="marketingCookies"
                  className="flex flex-col space-y-1 cursor-pointer"
                >
                  <span>Marketing Cookies</span>
                  <span className="font-normal leading-snug text-muted-foreground">
                    Used for tracking and advertising purposes.
                  </span>
                </Label>
                <Switch
                  id="marketingCookies"
                  name="marketing"
                  checked={staffData.user.cookiePreferences?.marketing ?? false}
                  onCheckedChange={(checked) =>
                    handleCookieChange(checked, "marketing")
                  }
                />
              </div>
            </div>
          </CardContent>
          <CardFooter className="border-t px-6 py-4">
            <Button
              onClick={() => handleSave("preferences")}
              disabled={saveMutation.isPending}
            >
              {saveMutation.isPending ? "Saving..." : "Save Preferences"}
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}
