/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/10Iw0ehVDhW
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function Community() {
  return (
    <section
      className="min-h-screen flex flex-col justify-center items-center bg-cover bg-center"
      style={{
        backgroundImage: "url('/placeholder.svg')",
      }}
    >
      <div className="px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl text-black">
              Welcome to Our Community
            </h1>
            <p className="mx-auto max-w-[700px] text-gray-200 md:text-xl dark:text-gray-400">
              Join our community and get the latest updates and news about our
              products and services.
            </p>
          </div>
          <div className="w-full max-w-sm space-y-2">
            <form className="flex space-x-2">
              <Input
                className="max-w-lg flex-1"
                placeholder="Enter your email"
                type="email"
              />
              <Button type="submit" className="bg-black text-white">
                Sign Up
              </Button>
            </form>
            <p className="text-xs text-gray-200 dark:text-gray-400">
              By signing up, you agree to our
              <Link href="#" className="underline underline-offset-2">
                Terms & Conditions
              </Link>
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
