/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/irxBRWEtqKH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function OnboardingFormStep1() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-50">
      <header className="flex items-center space-x-2 mb-8">
        <LogInIcon className="w-8 h-8 text-primary" />
        <h1 className="text-2xl font-bold">ConsultX</h1>
      </header>
      <div className="flex items-center space-x-4 mb-8">
        <div className="flex items-center justify-center w-10 h-10 rounded-full bg-primary text-white">1</div>
        <div className="w-10 h-0.5 bg-gray-300" />
        <div className="flex items-center justify-center w-10 h-10 rounded-full bg-gray-200 text-gray-500">2</div>
        <div className="w-10 h-0.5 bg-gray-300" />
        <div className="flex items-center justify-center w-10 h-10 rounded-full bg-gray-200 text-gray-500">3</div>
        <div className="w-10 h-0.5 bg-gray-300" />
        <div className="flex items-center justify-center w-10 h-10 rounded-full bg-gray-200 text-gray-500">4</div>
      </div>
      <div className="text-center mb-8">
        <h2 className="text-2xl font-bold">Welcome! First things first...</h2>
        <p className="text-muted-foreground">You can always change them later.</p>
      </div>
      <form className="w-full max-w-md space-y-4">
        <div className="space-y-2">
          <Label htmlFor="full-name">Full Name</Label>
          <Input id="full-name" placeholder="Steve Jobs" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="display-name">Display Name</Label>
          <Input id="display-name" placeholder="Steve" />
        </div>
        <Button className="w-full bg-primary text-white">Create Workspace</Button>
      </form>
    </div>
  )
}

function LogInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
