/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7C8g2UpU0QT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Pricing() {
  return (
    <div className="flex items-start gap-6 w-full max-w-[900px]">
      <div className="bg-card rounded-lg shadow-lg w-[320px]">
        <Tabs defaultValue="1-month" className="w-full">
          <TabsList className="grid grid-cols-4 border-b">
            <TabsTrigger value="1-month">1 Month</TabsTrigger>
            <TabsTrigger value="3-month">3 Months</TabsTrigger>
            <TabsTrigger value="6-month">6 Months</TabsTrigger>
            <TabsTrigger value="12-month">12 Months</TabsTrigger>
          </TabsList>
          <TabsContent value="1-month">
            <Card className="rounded-b-lg">
              <CardContent className="grid gap-4 p-6">
                <div className="flex items-center justify-between">
                  <div className="text-4xl font-bold">$99</div>
                  <div className="text-muted-foreground">per month</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Calls per week</div>
                  <div className="font-medium">1</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Email support</div>
                  <div className="font-medium">Unlimited</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Video meetings</div>
                  <div className="font-medium">1 per month</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Dedicated account manager</div>
                  <div className="font-medium">No</div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
          <TabsContent value="3-month">
            <Card className="rounded-b-lg">
              <CardContent className="grid gap-4 p-6">
                <div className="flex items-center justify-between">
                  <div className="text-4xl font-bold">$79</div>
                  <div className="text-muted-foreground">per month</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Calls per week</div>
                  <div className="font-medium">3</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Email support</div>
                  <div className="font-medium">Unlimited</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Video meetings</div>
                  <div className="font-medium">2 per month</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Dedicated account manager</div>
                  <div className="font-medium">No</div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
          <TabsContent value="6-month">
            <Card className="rounded-b-lg">
              <CardContent className="grid gap-4 p-6">
                <div className="flex items-center justify-between">
                  <div className="text-4xl font-bold">$59</div>
                  <div className="text-muted-foreground">per month</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Calls per week</div>
                  <div className="font-medium">6</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Email support</div>
                  <div className="font-medium">Unlimited</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Video meetings</div>
                  <div className="font-medium">4 per month</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Dedicated account manager</div>
                  <div className="font-medium">Yes</div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
          <TabsContent value="12-month">
            <Card className="rounded-b-lg">
              <CardContent className="grid gap-4 p-6">
                <div className="flex items-center justify-between">
                  <div className="text-4xl font-bold">$39</div>
                  <div className="text-muted-foreground">per month</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Calls per week</div>
                  <div className="font-medium">12</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Email support</div>
                  <div className="font-medium">Unlimited</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Video meetings</div>
                  <div className="font-medium">8 per month</div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Dedicated account manager</div>
                  <div className="font-medium">Yes</div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
      <div className="flex flex-col gap-4">
        <Button size="lg">Book a Call</Button>
        <Button size="lg" variant="outline">
          Contact Sales
        </Button>
        <Button size="lg" variant="outline">
          Learn More
        </Button>
        <Button size="lg" variant="outline">
          Try for Free
        </Button>
      </div>
    </div>
  )
}
