/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/r3WQJxLalyw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogClose } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function ProfilePictureDialog() {
  return (
    <Dialog defaultOpen>
      <DialogTrigger asChild>
        <Button variant="outline">Upload Profile Picture</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Update Profile Picture</DialogTitle>
          <DialogDescription>Upload a new profile picture to update your account.</DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid items-center gap-4">
            <div className="flex flex-col items-center justify-center">
              <img src="/placeholder.svg" alt="Profile Preview" className="rounded-full" />
              <p className="mt-2 text-sm text-muted-foreground">Preview of selected image</p>
            </div>
            <div className="flex flex-col space-y-1.5">
              <Label htmlFor="profile-picture">Profile Picture</Label>
              <Input id="profile-picture" type="file" />
            </div>
          </div>
        </div>
        <DialogFooter>
          <div>
            <Button variant="outline">Cancel</Button>
          </div>
          <Button type="submit">Update</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
