/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2Yay5t3hGGA
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardHeader, CardContent, Card } from "@/components/ui/card"

export function SearchExperts() {
  return (
    <div className="bg-white p-8 rounded-lg shadow-md">
      <h2 className="text-2xl font-bold mb-4">Find Your Next Consultant</h2>
      <div className="mb-6">
        <label className="sr-only" htmlFor="search">
          Search
        </label>
        <div className="flex items-center border-b-2 border-gray-200">
          <Input className="flex-1 py-2" id="search" placeholder="Search for consultants, domains, subdomains, etc." />
          <MicroscopeIcon className="text-yellow-500 w-6 h-6" />
          <SettingsIcon className="text-gray-500 w-6 h-6 ml-4" />
        </div>
      </div>
      <div className="mb-4">
        <h3 className="font-semibold mb-2">DOMAINS</h3>
        <div className="flex space-x-2 flex-wrap">
          <Button variant="outline">Finance</Button>
          <Button variant="outline">Human Resources</Button>
          <Button variant="outline">Marketing</Button>
          <Button variant="outline">Information Technology</Button>
          <Button variant="outline">Operations</Button>
        </div>
      </div>
      <div className="mb-4">
        <h3 className="font-semibold mb-2">SUBDOMAINS</h3>
        <div className="flex space-x-2 flex-wrap">
          <Button variant="outline">Risk Management</Button>
          <Button variant="outline">Training and Development</Button>
          <Button variant="outline">Digital Marketing</Button>
          <Button variant="outline">Data Analysis</Button>
          <Button variant="outline">Supply Chain</Button>
        </div>
      </div>
      <div className="mb-6">
        <h3 className="font-semibold mb-2">ORDER BY</h3>
        <div className="flex space-x-2">
          <Button variant="outline">Name A - Z</Button>
          <Button variant="outline">Name Z - A</Button>
          <Button variant="outline">Domain A - Z</Button>
          <Button variant="outline">Domain Z - A</Button>
          <Button variant="outline">Recent</Button>
          <Button variant="outline">Oldest</Button>
        </div>
      </div>
      <div className="mb-6">
        <label className="flex items-center mb-2" htmlFor="available">
          <input className="mr-2" id="available" type="checkbox" />
          ONLY SHOW CONSULTANTS CURRENTLY AVAILABLE
        </label>
        <label className="flex items-center" htmlFor="remote">
          <input className="mr-2" id="remote" type="checkbox" />
          INCLUDE CONSULTANTS AVAILABLE FOR REMOTE WORK
        </label>
      </div>
      <div className="mb-6">
        <Button className="bg-red-500 text-white">RESET SEARCH</Button>
      </div>
      <div className="grid grid-cols-2 gap-4">
        <Card className="mb-4">
          <CardHeader className="flex items-center space-x-4">
            <img
              alt="Consultant Profile"
              className="rounded-full"
              height="50"
              src="/placeholder.svg"
              style={{
                aspectRatio: "50/50",
                objectFit: "cover",
              }}
              width="50"
            />
            <div>
              <h3 className="font-semibold">Consultant Name</h3>
              <p className="text-gray-500">Domain</p>
            </div>
          </CardHeader>
          <CardContent>
            <p className="mb-2">
              Short description about the consultant. This could include their expertise, years of experience, etc.
            </p>
            <Button variant="outline">View Profile</Button>
          </CardContent>
        </Card>
        <Card className="mb-4">
          <CardHeader className="flex items-center space-x-4">
            <img
              alt="Consultant Profile"
              className="rounded-full"
              height="50"
              src="/placeholder.svg"
              style={{
                aspectRatio: "50/50",
                objectFit: "cover",
              }}
              width="50"
            />
            <div>
              <h3 className="font-semibold">Consultant Name</h3>
              <p className="text-gray-500">Domain</p>
            </div>
          </CardHeader>
          <CardContent>
            <p className="mb-2">
              Short description about the consultant. This could include their expertise, years of experience, etc.
            </p>
            <Button variant="outline">View Profile</Button>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}


function MicroscopeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 18h8" />
      <path d="M3 22h18" />
      <path d="M14 22a7 7 0 1 0 0-14h-1" />
      <path d="M9 14h2" />
      <path d="M9 12a2 2 0 0 1-2-2V6h6v4a2 2 0 0 1-2 2Z" />
      <path d="M12 6V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3" />
    </svg>
  )
}


function SettingsIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
