/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jJE8bZmoH1K
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function UserSignupEmailTemplate() {
  return (
    <div className="bg-white dark:bg-gray-950 text-gray-900 dark:text-gray-50 rounded-lg p-6 max-w-[600px] mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-2">
          <MountainIcon className="h-8 w-8" />
          <span className="text-xl font-semibold">ConsultX</span>
        </div>
        <div className="text-sm text-gray-500 dark:text-gray-400">Welcome Aboard!</div>
      </div>
      <div className="space-y-4">
        <h2 className="text-2xl font-bold">Activate Your Account</h2>
        <p className="text-gray-500 dark:text-gray-400">
          Thank you for signing up with ConsultX. To get started, please click the button below to activate your new
          account.
        </p>
        <div className="flex justify-center">
          <Button>Activate Account</Button>
        </div>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          If you have any questions or need assistance, please don't hesitate to reach out to our support team at
          support@consultx.com.
        </p>
      </div>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
