/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q78qlbK
 */
import {
  AccordionTrigger,
  AccordionContent,
  AccordionItem,
  Accordion,
} from "@/components/ui/accordion";
import { CardContent, Card } from "@/components/ui/card";
export function FAQ() {
  return (
    <div className="flex justify-center items-center py-10">
      <Card className="shadow-lg w-[1200px]">
        <CardContent className="p-6">
          <h2 className="text-2xl font-semibold">Frequently Asked Questions</h2>
          <Accordion className="w-full mt-4" type="multiple">
            <AccordionItem value="item-1">
              <AccordionTrigger className="hover:underline-none">
                What services does our consultancy provide?
              </AccordionTrigger>
              <AccordionContent>
                We offer a range of services including business strategy, market
                research, and project management.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-2">
              <AccordionTrigger className="hover:underline-none">
                How can our consultancy help your business grow?
              </AccordionTrigger>
              <AccordionContent>
                We provide expert advice and strategies tailored to your
                business needs, helping you to improve efficiency and increase
                profits.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-3">
              <AccordionTrigger className="hover:underline-none">
                What industries do we specialize in?
              </AccordionTrigger>
              <AccordionContent>
                Our consultants have experience in a wide range of industries,
                including technology, healthcare, and finance.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-4">
              <AccordionTrigger className="hover:underline-none">
                How can you get started with our consultancy?
              </AccordionTrigger>
              <AccordionContent>
                Contact us to schedule a consultation. We will discuss your
                business needs and how our services can help you achieve your
                goals.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem className="border-b-0" value="item-5">
              <AccordionTrigger className="hover:underline-none">
                What is our consultancy approach to problem-solving?
              </AccordionTrigger>
              <AccordionContent>
                We use a collaborative approach, working closely with your team
                to understand your business and develop effective solutions.
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </CardContent>
      </Card>
    </div>
  );
}
