"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LRQCtQXmRHY
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { signIn, useSession } from "next-auth/react";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function SignIn() {
  const { data: session } = useSession();

  const router = useRouter();
  if (session) {
    router.push("/");
  }
  return (
    <div className="min-h-screen flex">
      <div className="w-1/2 bg-gray-100 text-black p-12 flex flex-col justify-between">
        <Link href="/">
          <div className="flex items-center justify-start space-x-2">
            <GlobeIcon className="text-black w-6 h-6" />
            <h1 className="text-4xl font-semibold">ConsultX</h1>
          </div>
        </Link>
        <div>
          <blockquote>
            “This library has saved me countless hours of work and helped me
            deliver stunning designs to my clients faster than ever before.”
          </blockquote>
          <p className="mt-4">Sofia Davis</p>
        </div>
        <div className="text-sm">
          Built by shadcn. The source code is available on GitHub.
        </div>
      </div>
      <div className="w-1/2 bg-gray-900 text-white p-12 flex flex-col justify-center">
        <div className="flex flex-col p-20">
          <h2 className="text-3xl font-semibold mb-6">Create an account</h2>
          <p className="mb-6">Enter your email below to create your account</p>
          <Input placeholder="name@example.com" />
          <Button
            className="w-full mt-4 bg-gray-800 hover:bg-gray-700
          "
          >
            Sign In with Email
          </Button>
          <div className="relative my-6">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-gray-600" />
            </div>
            <div className="relative flex justify-center text-sm">
              <span className="px-2 bg-gray-900 text-gray-400">
                OR CONTINUE WITH
              </span>
            </div>
          </div>
          <Button
            className="w-full flex items-center justify-center bg-black hover:bg-gray-700"
            onClick={() => signIn("github")}
          >
            <GithubIcon className="w-6 h-6 text-white mr-2" />
            Github
          </Button>
          <Button
            className="w-full flex items-center justify-center mt-4 bg-red-600 hover:bg-red-500"
            onClick={() => signIn("google")}
          >
            <ChromeIcon className="w-6 h-6 text-white mr-2" />
            Google
          </Button>
          <Button
            className="w-full flex items-center justify-center mt-4 bg-blue-600 hover:bg-blue-500"
            onClick={() => signIn("facebook")}
          >
            <FacebookIcon className="w-6 h-6 text-white mr-2" />
            Facebook
          </Button>
          <p className="text-xs text-gray-400 mt-6">
            By clicking continue, you agree to our Terms of Service and Privacy
            Policy.
          </p>
        </div>
        <div />
      </div>
    </div>
  );
}

function GlobeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
  );
}

function GithubIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function ChromeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  );
}

function FacebookIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  );
}
