/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jJE8bZmoH1K
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Text,
  Button,
} from "@react-email/components";
import * as React from "react";

interface UserSignupEmailProps {
  name: string;
}

export const UserSignupEmail: React.FC<Readonly<UserSignupEmailProps>> = ({
  name,
}) => (
  <Html>
    <Head />
    <Preview>Activate Your Account</Preview>
    <Body style={main}>
      <Container style={container}>
        <div style={header}>
          <div style={logo}>
            <MountainIcon style={icon} />
            <span style={logoText}>ConsultX</span>
          </div>
          <Text style={headerText}>Welcome Aboard!</Text>
        </div>
        <div style={content}>
          <Heading style={h2}>Activate Your Account</Heading>
          <Text style={text}>
            Thank you for signing up with ConsultX. To get started, please click
            the button below to activate your new account.
          </Text>
          <div style={buttonWrapper}>
            <Button style={button} href="#">
              Activate Account
            </Button>
          </div>
          <Text style={footerText}>
            If you have any questions or need assistance, please don't hesitate
            to reach out to our support team at support@consultx.com.
          </Text>
        </div>
      </Container>
    </Body>
  </Html>
);

export default UserSignupEmail;

const MountainIcon = (props) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
  </svg>
);

const main = {
  backgroundColor: "#ffffff",
  margin: "0 auto",
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
};

const container = {
  margin: "auto",
  padding: "24px",
  borderRadius: "8px",
  maxWidth: "600px",
};

const header = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: "24px",
};

const logo = {
  display: "flex",
  alignItems: "center",
  gap: "8px",
};

const icon = {
  height: "32px",
  width: "32px",
};

const logoText = {
  fontSize: "24px",
  fontWeight: "600",
};

const headerText = {
  fontSize: "14px",
  color: "#6B7280",
};

const content = {
  display: "flex",
  flexDirection: "column",
  gap: "16px",
};

const h2 = {
  fontSize: "24px",
  fontWeight: "700",
  margin: "0",
};

const text = {
  fontSize: "16px",
  color: "#6B7280",
  margin: "0",
};

const buttonWrapper = {
  display: "flex",
  justifyContent: "center",
};

const button = {
  background: "linear-gradient(to right, #000000, #C0C0C0)",
  color: "#ffffff",
  fontSize: "16px",
  fontWeight: "600",
  padding: "12px 24px",
  borderRadius: "6px",
  textDecoration: "none",
};

const footerText = {
  fontSize: "14px",
  color: "#6B7280",
  margin: "0",
};
